<?php
// $Id: jscrollpane.module,v 1.1 2008/02/17 21:53:54 stevemckenzie Exp $

/**
 * API function to add jScrollpane on a page.
 *
 * @code
 *   // foo class will get default scroll.
 *   $commands[] = array('selector' => '.foo');
 *
 *   // bar ID will get scroll with min and max scroll set to 80px.
 *   $commands[] = array(
 *    'selector' => '#bar',
 *    'options' => array(
 *      'verticalDragMinHeight' => 80,
 *      'verticalDragMaxHeight' => 80,
 *    ),
 *   );
 *
 *   jscrollpane_add_jscroll($commands);
 * @endcode
 */
function jscroll_add_jscroll($commands = array()) {
  // Add the JS plugin and CSS.
  jscroll_add_media();
  $settings['jscroll']['commands'] = array();

  foreach ($commands as $key => $command) {
    if (!empty($command['selector'])) {
      // Add default values.
      $command += array(
        'options' => array(),
      );

      $settings['jscroll']['commands'][] = $command;
    }
  }
  drupal_add_js($settings, 'setting');
}

/**
 *  Add the jQuery plugin.
 */
function jscroll_add_media() {
  static $include;

  if (!$include) {
    // TODO: Move to libraries folder.
    drupal_add_js(drupal_get_path('module', 'jscroll') . '/jquery.jscroll.js');
    drupal_add_css(drupal_get_path('module', 'jscroll') . '/scrollbar.css');

    // Add our own JS.
    drupal_add_js(drupal_get_path('module', 'jscroll') . '/jscroll.js');
    $include = TRUE;
  }
}