<?php
// $Id: jscrollpane.module,v 1.1 2008/02/17 21:53:54 stevemckenzie Exp $

/**
 * API function to add jScrollpane on a page.
 *
 * @code
 *   // foo class will get default scroll.
 *   $commands[] = array('selector' => '.foo');
 *
 *   // bar ID will get scroll with min and max scroll set to 80px.
 *   $commands[] = array(
 *    'selector' => '#bar',
 *    'options' => array(
 *      'verticalDragMinHeight' => 80,
 *      'verticalDragMaxHeight' => 80,
 *    ),
 *   );
 *
 *   jscrollpane_add_jscroll($commands);
 * @endcode
 */
function jscrollpane_add_jscroll($commands = array()) {
  // Add the JS plugin and CSS.
  drupal_add_library('jscrollpane', 'jscrollpane.jscroll');

  $settings['jscrollpane']['commands'] = array();

  foreach ($commands as $key => $command) {
    if (!empty($command['selector'])) {
      // Add default values.
      $command += array(
        'options' => array(),
      );

      $settings['jscrollpane']['commands'][] = $command;
    }
  }

  // Add our custom JS.
  drupal_add_js(drupal_get_path('module', 'jscrollpane') . '/jscrollpane.js');
  drupal_add_js($settings, 'setting');
}

/**
 * Implements hook_library().
 */
function jscrollpane_library() {
  $libraries['jscrollpane.jscroll'] = array(
    'title' => 'jScrollPane',
    'website' => 'https://github.com/vitch/jScrollPane',
    'version' => '2.0',
    'js' => array(
      libraries_get_path('jscrollpane') . '/script/jquery.jscrollpane.js' => array(),
      libraries_get_path('jscrollpane') . '/script/jquery.mousewheel.js' => array(),
    ),
    'css' => array(
      libraries_get_path('jscrollpane') . '/style/jquery.jscrollpane.css' => array(),
    ),
  );

  return $libraries;
}